//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SushiApp.wsComuna {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebService/", ConfigurationName="wsComuna.ServiceComuna")]
    public interface ServiceComuna {
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceComuna/eliminarComunaRequest", ReplyAction="http://WebService/ServiceComuna/eliminarComunaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsComuna.eliminarComunaResponse eliminarComuna(SushiApp.wsComuna.eliminarComunaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceComuna/eliminarComunaRequest", ReplyAction="http://WebService/ServiceComuna/eliminarComunaResponse")]
        System.Threading.Tasks.Task<SushiApp.wsComuna.eliminarComunaResponse> eliminarComunaAsync(SushiApp.wsComuna.eliminarComunaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceComuna/obtenerComunaRequest", ReplyAction="http://WebService/ServiceComuna/obtenerComunaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SushiApp.wsComuna.obtenerComunaResponse obtenerComuna(SushiApp.wsComuna.obtenerComunaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceComuna/obtenerComunaRequest", ReplyAction="http://WebService/ServiceComuna/obtenerComunaResponse")]
        System.Threading.Tasks.Task<SushiApp.wsComuna.obtenerComunaResponse> obtenerComunaAsync(SushiApp.wsComuna.obtenerComunaRequest request);
        
        // CODEGEN: El parámetro 'comuna' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceComuna/agregarComunaRequest", ReplyAction="http://WebService/ServiceComuna/agregarComunaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsComuna.agregarComunaResponse agregarComuna(SushiApp.wsComuna.agregarComunaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceComuna/agregarComunaRequest", ReplyAction="http://WebService/ServiceComuna/agregarComunaResponse")]
        System.Threading.Tasks.Task<SushiApp.wsComuna.agregarComunaResponse> agregarComunaAsync(SushiApp.wsComuna.agregarComunaRequest request);
        
        // CODEGEN: El parámetro 'comuna' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceComuna/modificarComunaRequest", ReplyAction="http://WebService/ServiceComuna/modificarComunaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsComuna.modificarComunaResponse modificarComuna(SushiApp.wsComuna.modificarComunaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceComuna/modificarComunaRequest", ReplyAction="http://WebService/ServiceComuna/modificarComunaResponse")]
        System.Threading.Tasks.Task<SushiApp.wsComuna.modificarComunaResponse> modificarComunaAsync(SushiApp.wsComuna.modificarComunaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceComuna/buscarComunaRequest", ReplyAction="http://WebService/ServiceComuna/buscarComunaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SushiApp.wsComuna.buscarComunaResponse buscarComuna(SushiApp.wsComuna.buscarComunaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceComuna/buscarComunaRequest", ReplyAction="http://WebService/ServiceComuna/buscarComunaResponse")]
        System.Threading.Tasks.Task<SushiApp.wsComuna.buscarComunaResponse> buscarComunaAsync(SushiApp.wsComuna.buscarComunaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarComuna", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class eliminarComunaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarComunaRequest() {
        }
        
        public eliminarComunaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarComunaResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class eliminarComunaResponse {
        
        public eliminarComunaResponse() {
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService/")]
    public partial class comuna : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int comunaIdField;
        
        private string comunaNombreField;
        
        private int provinciaIdField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int comunaId {
            get {
                return this.comunaIdField;
            }
            set {
                this.comunaIdField = value;
                this.RaisePropertyChanged("comunaId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string comunaNombre {
            get {
                return this.comunaNombreField;
            }
            set {
                this.comunaNombreField = value;
                this.RaisePropertyChanged("comunaNombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int provinciaId {
            get {
                return this.provinciaIdField;
            }
            set {
                this.provinciaIdField = value;
                this.RaisePropertyChanged("provinciaId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerComuna", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerComunaRequest {
        
        public obtenerComunaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerComunaResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerComunaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsComuna.comuna[] @return;
        
        public obtenerComunaResponse() {
        }
        
        public obtenerComunaResponse(SushiApp.wsComuna.comuna[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarComuna", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class agregarComunaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsComuna.comuna comuna;
        
        public agregarComunaRequest() {
        }
        
        public agregarComunaRequest(SushiApp.wsComuna.comuna comuna) {
            this.comuna = comuna;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarComunaResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class agregarComunaResponse {
        
        public agregarComunaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarComuna", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class modificarComunaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsComuna.comuna comuna;
        
        public modificarComunaRequest() {
        }
        
        public modificarComunaRequest(SushiApp.wsComuna.comuna comuna) {
            this.comuna = comuna;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarComunaResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class modificarComunaResponse {
        
        public modificarComunaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarComuna", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class buscarComunaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarComunaRequest() {
        }
        
        public buscarComunaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarComunaResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class buscarComunaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsComuna.comuna @return;
        
        public buscarComunaResponse() {
        }
        
        public buscarComunaResponse(SushiApp.wsComuna.comuna @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceComunaChannel : SushiApp.wsComuna.ServiceComuna, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceComunaClient : System.ServiceModel.ClientBase<SushiApp.wsComuna.ServiceComuna>, SushiApp.wsComuna.ServiceComuna {
        
        public ServiceComunaClient() {
        }
        
        public ServiceComunaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceComunaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceComunaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceComunaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsComuna.eliminarComunaResponse SushiApp.wsComuna.ServiceComuna.eliminarComuna(SushiApp.wsComuna.eliminarComunaRequest request) {
            return base.Channel.eliminarComuna(request);
        }
        
        public void eliminarComuna(int id) {
            SushiApp.wsComuna.eliminarComunaRequest inValue = new SushiApp.wsComuna.eliminarComunaRequest();
            inValue.id = id;
            SushiApp.wsComuna.eliminarComunaResponse retVal = ((SushiApp.wsComuna.ServiceComuna)(this)).eliminarComuna(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsComuna.eliminarComunaResponse> SushiApp.wsComuna.ServiceComuna.eliminarComunaAsync(SushiApp.wsComuna.eliminarComunaRequest request) {
            return base.Channel.eliminarComunaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsComuna.eliminarComunaResponse> eliminarComunaAsync(int id) {
            SushiApp.wsComuna.eliminarComunaRequest inValue = new SushiApp.wsComuna.eliminarComunaRequest();
            inValue.id = id;
            return ((SushiApp.wsComuna.ServiceComuna)(this)).eliminarComunaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsComuna.obtenerComunaResponse SushiApp.wsComuna.ServiceComuna.obtenerComuna(SushiApp.wsComuna.obtenerComunaRequest request) {
            return base.Channel.obtenerComuna(request);
        }
        
        public SushiApp.wsComuna.comuna[] obtenerComuna() {
            SushiApp.wsComuna.obtenerComunaRequest inValue = new SushiApp.wsComuna.obtenerComunaRequest();
            SushiApp.wsComuna.obtenerComunaResponse retVal = ((SushiApp.wsComuna.ServiceComuna)(this)).obtenerComuna(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsComuna.obtenerComunaResponse> SushiApp.wsComuna.ServiceComuna.obtenerComunaAsync(SushiApp.wsComuna.obtenerComunaRequest request) {
            return base.Channel.obtenerComunaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsComuna.obtenerComunaResponse> obtenerComunaAsync() {
            SushiApp.wsComuna.obtenerComunaRequest inValue = new SushiApp.wsComuna.obtenerComunaRequest();
            return ((SushiApp.wsComuna.ServiceComuna)(this)).obtenerComunaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsComuna.agregarComunaResponse SushiApp.wsComuna.ServiceComuna.agregarComuna(SushiApp.wsComuna.agregarComunaRequest request) {
            return base.Channel.agregarComuna(request);
        }
        
        public void agregarComuna(SushiApp.wsComuna.comuna comuna) {
            SushiApp.wsComuna.agregarComunaRequest inValue = new SushiApp.wsComuna.agregarComunaRequest();
            inValue.comuna = comuna;
            SushiApp.wsComuna.agregarComunaResponse retVal = ((SushiApp.wsComuna.ServiceComuna)(this)).agregarComuna(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsComuna.agregarComunaResponse> SushiApp.wsComuna.ServiceComuna.agregarComunaAsync(SushiApp.wsComuna.agregarComunaRequest request) {
            return base.Channel.agregarComunaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsComuna.agregarComunaResponse> agregarComunaAsync(SushiApp.wsComuna.comuna comuna) {
            SushiApp.wsComuna.agregarComunaRequest inValue = new SushiApp.wsComuna.agregarComunaRequest();
            inValue.comuna = comuna;
            return ((SushiApp.wsComuna.ServiceComuna)(this)).agregarComunaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsComuna.modificarComunaResponse SushiApp.wsComuna.ServiceComuna.modificarComuna(SushiApp.wsComuna.modificarComunaRequest request) {
            return base.Channel.modificarComuna(request);
        }
        
        public void modificarComuna(SushiApp.wsComuna.comuna comuna) {
            SushiApp.wsComuna.modificarComunaRequest inValue = new SushiApp.wsComuna.modificarComunaRequest();
            inValue.comuna = comuna;
            SushiApp.wsComuna.modificarComunaResponse retVal = ((SushiApp.wsComuna.ServiceComuna)(this)).modificarComuna(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsComuna.modificarComunaResponse> SushiApp.wsComuna.ServiceComuna.modificarComunaAsync(SushiApp.wsComuna.modificarComunaRequest request) {
            return base.Channel.modificarComunaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsComuna.modificarComunaResponse> modificarComunaAsync(SushiApp.wsComuna.comuna comuna) {
            SushiApp.wsComuna.modificarComunaRequest inValue = new SushiApp.wsComuna.modificarComunaRequest();
            inValue.comuna = comuna;
            return ((SushiApp.wsComuna.ServiceComuna)(this)).modificarComunaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsComuna.buscarComunaResponse SushiApp.wsComuna.ServiceComuna.buscarComuna(SushiApp.wsComuna.buscarComunaRequest request) {
            return base.Channel.buscarComuna(request);
        }
        
        public SushiApp.wsComuna.comuna buscarComuna(int id) {
            SushiApp.wsComuna.buscarComunaRequest inValue = new SushiApp.wsComuna.buscarComunaRequest();
            inValue.id = id;
            SushiApp.wsComuna.buscarComunaResponse retVal = ((SushiApp.wsComuna.ServiceComuna)(this)).buscarComuna(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsComuna.buscarComunaResponse> SushiApp.wsComuna.ServiceComuna.buscarComunaAsync(SushiApp.wsComuna.buscarComunaRequest request) {
            return base.Channel.buscarComunaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsComuna.buscarComunaResponse> buscarComunaAsync(int id) {
            SushiApp.wsComuna.buscarComunaRequest inValue = new SushiApp.wsComuna.buscarComunaRequest();
            inValue.id = id;
            return ((SushiApp.wsComuna.ServiceComuna)(this)).buscarComunaAsync(inValue);
        }
    }
}
