//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SushiApp.wsRegion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebService/", ConfigurationName="wsRegion.ServiceRegion")]
    public interface ServiceRegion {
        
        // CODEGEN: El parámetro 'region' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceRegion/agregarRegionRequest", ReplyAction="http://WebService/ServiceRegion/agregarRegionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsRegion.agregarRegionResponse agregarRegion(SushiApp.wsRegion.agregarRegionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceRegion/agregarRegionRequest", ReplyAction="http://WebService/ServiceRegion/agregarRegionResponse")]
        System.Threading.Tasks.Task<SushiApp.wsRegion.agregarRegionResponse> agregarRegionAsync(SushiApp.wsRegion.agregarRegionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceRegion/buscarRegionRequest", ReplyAction="http://WebService/ServiceRegion/buscarRegionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SushiApp.wsRegion.buscarRegionResponse buscarRegion(SushiApp.wsRegion.buscarRegionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceRegion/buscarRegionRequest", ReplyAction="http://WebService/ServiceRegion/buscarRegionResponse")]
        System.Threading.Tasks.Task<SushiApp.wsRegion.buscarRegionResponse> buscarRegionAsync(SushiApp.wsRegion.buscarRegionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceRegion/obtenerRegionRequest", ReplyAction="http://WebService/ServiceRegion/obtenerRegionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SushiApp.wsRegion.obtenerRegionResponse obtenerRegion(SushiApp.wsRegion.obtenerRegionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceRegion/obtenerRegionRequest", ReplyAction="http://WebService/ServiceRegion/obtenerRegionResponse")]
        System.Threading.Tasks.Task<SushiApp.wsRegion.obtenerRegionResponse> obtenerRegionAsync(SushiApp.wsRegion.obtenerRegionRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceRegion/eliminarRegionRequest", ReplyAction="http://WebService/ServiceRegion/eliminarRegionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsRegion.eliminarRegionResponse eliminarRegion(SushiApp.wsRegion.eliminarRegionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceRegion/eliminarRegionRequest", ReplyAction="http://WebService/ServiceRegion/eliminarRegionResponse")]
        System.Threading.Tasks.Task<SushiApp.wsRegion.eliminarRegionResponse> eliminarRegionAsync(SushiApp.wsRegion.eliminarRegionRequest request);
        
        // CODEGEN: El parámetro 'region' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceRegion/modificarRegionRequest", ReplyAction="http://WebService/ServiceRegion/modificarRegionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsRegion.modificarRegionResponse modificarRegion(SushiApp.wsRegion.modificarRegionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceRegion/modificarRegionRequest", ReplyAction="http://WebService/ServiceRegion/modificarRegionResponse")]
        System.Threading.Tasks.Task<SushiApp.wsRegion.modificarRegionResponse> modificarRegionAsync(SushiApp.wsRegion.modificarRegionRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService/")]
    public partial class region : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int regionIdField;
        
        private string regionNombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int regionId {
            get {
                return this.regionIdField;
            }
            set {
                this.regionIdField = value;
                this.RaisePropertyChanged("regionId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string regionNombre {
            get {
                return this.regionNombreField;
            }
            set {
                this.regionNombreField = value;
                this.RaisePropertyChanged("regionNombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarRegion", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class agregarRegionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsRegion.region region;
        
        public agregarRegionRequest() {
        }
        
        public agregarRegionRequest(SushiApp.wsRegion.region region) {
            this.region = region;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarRegionResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class agregarRegionResponse {
        
        public agregarRegionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarRegion", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class buscarRegionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarRegionRequest() {
        }
        
        public buscarRegionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarRegionResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class buscarRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsRegion.region @return;
        
        public buscarRegionResponse() {
        }
        
        public buscarRegionResponse(SushiApp.wsRegion.region @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerRegion", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerRegionRequest {
        
        public obtenerRegionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerRegionResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsRegion.region[] @return;
        
        public obtenerRegionResponse() {
        }
        
        public obtenerRegionResponse(SushiApp.wsRegion.region[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRegion", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class eliminarRegionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarRegionRequest() {
        }
        
        public eliminarRegionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRegionResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class eliminarRegionResponse {
        
        public eliminarRegionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarRegion", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class modificarRegionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsRegion.region region;
        
        public modificarRegionRequest() {
        }
        
        public modificarRegionRequest(SushiApp.wsRegion.region region) {
            this.region = region;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarRegionResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class modificarRegionResponse {
        
        public modificarRegionResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceRegionChannel : SushiApp.wsRegion.ServiceRegion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRegionClient : System.ServiceModel.ClientBase<SushiApp.wsRegion.ServiceRegion>, SushiApp.wsRegion.ServiceRegion {
        
        public ServiceRegionClient() {
        }
        
        public ServiceRegionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRegionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRegionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRegionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsRegion.agregarRegionResponse SushiApp.wsRegion.ServiceRegion.agregarRegion(SushiApp.wsRegion.agregarRegionRequest request) {
            return base.Channel.agregarRegion(request);
        }
        
        public void agregarRegion(SushiApp.wsRegion.region region) {
            SushiApp.wsRegion.agregarRegionRequest inValue = new SushiApp.wsRegion.agregarRegionRequest();
            inValue.region = region;
            SushiApp.wsRegion.agregarRegionResponse retVal = ((SushiApp.wsRegion.ServiceRegion)(this)).agregarRegion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsRegion.agregarRegionResponse> SushiApp.wsRegion.ServiceRegion.agregarRegionAsync(SushiApp.wsRegion.agregarRegionRequest request) {
            return base.Channel.agregarRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsRegion.agregarRegionResponse> agregarRegionAsync(SushiApp.wsRegion.region region) {
            SushiApp.wsRegion.agregarRegionRequest inValue = new SushiApp.wsRegion.agregarRegionRequest();
            inValue.region = region;
            return ((SushiApp.wsRegion.ServiceRegion)(this)).agregarRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsRegion.buscarRegionResponse SushiApp.wsRegion.ServiceRegion.buscarRegion(SushiApp.wsRegion.buscarRegionRequest request) {
            return base.Channel.buscarRegion(request);
        }
        
        public SushiApp.wsRegion.region buscarRegion(int id) {
            SushiApp.wsRegion.buscarRegionRequest inValue = new SushiApp.wsRegion.buscarRegionRequest();
            inValue.id = id;
            SushiApp.wsRegion.buscarRegionResponse retVal = ((SushiApp.wsRegion.ServiceRegion)(this)).buscarRegion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsRegion.buscarRegionResponse> SushiApp.wsRegion.ServiceRegion.buscarRegionAsync(SushiApp.wsRegion.buscarRegionRequest request) {
            return base.Channel.buscarRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsRegion.buscarRegionResponse> buscarRegionAsync(int id) {
            SushiApp.wsRegion.buscarRegionRequest inValue = new SushiApp.wsRegion.buscarRegionRequest();
            inValue.id = id;
            return ((SushiApp.wsRegion.ServiceRegion)(this)).buscarRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsRegion.obtenerRegionResponse SushiApp.wsRegion.ServiceRegion.obtenerRegion(SushiApp.wsRegion.obtenerRegionRequest request) {
            return base.Channel.obtenerRegion(request);
        }
        
        public SushiApp.wsRegion.region[] obtenerRegion() {
            SushiApp.wsRegion.obtenerRegionRequest inValue = new SushiApp.wsRegion.obtenerRegionRequest();
            SushiApp.wsRegion.obtenerRegionResponse retVal = ((SushiApp.wsRegion.ServiceRegion)(this)).obtenerRegion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsRegion.obtenerRegionResponse> SushiApp.wsRegion.ServiceRegion.obtenerRegionAsync(SushiApp.wsRegion.obtenerRegionRequest request) {
            return base.Channel.obtenerRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsRegion.obtenerRegionResponse> obtenerRegionAsync() {
            SushiApp.wsRegion.obtenerRegionRequest inValue = new SushiApp.wsRegion.obtenerRegionRequest();
            return ((SushiApp.wsRegion.ServiceRegion)(this)).obtenerRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsRegion.eliminarRegionResponse SushiApp.wsRegion.ServiceRegion.eliminarRegion(SushiApp.wsRegion.eliminarRegionRequest request) {
            return base.Channel.eliminarRegion(request);
        }
        
        public void eliminarRegion(int id) {
            SushiApp.wsRegion.eliminarRegionRequest inValue = new SushiApp.wsRegion.eliminarRegionRequest();
            inValue.id = id;
            SushiApp.wsRegion.eliminarRegionResponse retVal = ((SushiApp.wsRegion.ServiceRegion)(this)).eliminarRegion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsRegion.eliminarRegionResponse> SushiApp.wsRegion.ServiceRegion.eliminarRegionAsync(SushiApp.wsRegion.eliminarRegionRequest request) {
            return base.Channel.eliminarRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsRegion.eliminarRegionResponse> eliminarRegionAsync(int id) {
            SushiApp.wsRegion.eliminarRegionRequest inValue = new SushiApp.wsRegion.eliminarRegionRequest();
            inValue.id = id;
            return ((SushiApp.wsRegion.ServiceRegion)(this)).eliminarRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsRegion.modificarRegionResponse SushiApp.wsRegion.ServiceRegion.modificarRegion(SushiApp.wsRegion.modificarRegionRequest request) {
            return base.Channel.modificarRegion(request);
        }
        
        public void modificarRegion(SushiApp.wsRegion.region region) {
            SushiApp.wsRegion.modificarRegionRequest inValue = new SushiApp.wsRegion.modificarRegionRequest();
            inValue.region = region;
            SushiApp.wsRegion.modificarRegionResponse retVal = ((SushiApp.wsRegion.ServiceRegion)(this)).modificarRegion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsRegion.modificarRegionResponse> SushiApp.wsRegion.ServiceRegion.modificarRegionAsync(SushiApp.wsRegion.modificarRegionRequest request) {
            return base.Channel.modificarRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsRegion.modificarRegionResponse> modificarRegionAsync(SushiApp.wsRegion.region region) {
            SushiApp.wsRegion.modificarRegionRequest inValue = new SushiApp.wsRegion.modificarRegionRequest();
            inValue.region = region;
            return ((SushiApp.wsRegion.ServiceRegion)(this)).modificarRegionAsync(inValue);
        }
    }
}
