//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SushiApp.wsCanal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebService/", ConfigurationName="wsCanal.ServiceCanal")]
    public interface ServiceCanal {
        
        // CODEGEN: El parámetro 'canal' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceCanal/modificarCanalRequest", ReplyAction="http://WebService/ServiceCanal/modificarCanalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsCanal.modificarCanalResponse modificarCanal(SushiApp.wsCanal.modificarCanalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceCanal/modificarCanalRequest", ReplyAction="http://WebService/ServiceCanal/modificarCanalResponse")]
        System.Threading.Tasks.Task<SushiApp.wsCanal.modificarCanalResponse> modificarCanalAsync(SushiApp.wsCanal.modificarCanalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceCanal/obtenerCanalRequest", ReplyAction="http://WebService/ServiceCanal/obtenerCanalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SushiApp.wsCanal.obtenerCanalResponse obtenerCanal(SushiApp.wsCanal.obtenerCanalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceCanal/obtenerCanalRequest", ReplyAction="http://WebService/ServiceCanal/obtenerCanalResponse")]
        System.Threading.Tasks.Task<SushiApp.wsCanal.obtenerCanalResponse> obtenerCanalAsync(SushiApp.wsCanal.obtenerCanalRequest request);
        
        // CODEGEN: El parámetro 'canal' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceCanal/agregarCanalRequest", ReplyAction="http://WebService/ServiceCanal/agregarCanalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsCanal.agregarCanalResponse agregarCanal(SushiApp.wsCanal.agregarCanalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceCanal/agregarCanalRequest", ReplyAction="http://WebService/ServiceCanal/agregarCanalResponse")]
        System.Threading.Tasks.Task<SushiApp.wsCanal.agregarCanalResponse> agregarCanalAsync(SushiApp.wsCanal.agregarCanalRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceCanal/eliminarCanalRequest", ReplyAction="http://WebService/ServiceCanal/eliminarCanalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsCanal.eliminarCanalResponse eliminarCanal(SushiApp.wsCanal.eliminarCanalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceCanal/eliminarCanalRequest", ReplyAction="http://WebService/ServiceCanal/eliminarCanalResponse")]
        System.Threading.Tasks.Task<SushiApp.wsCanal.eliminarCanalResponse> eliminarCanalAsync(SushiApp.wsCanal.eliminarCanalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceCanal/buscarCanalRequest", ReplyAction="http://WebService/ServiceCanal/buscarCanalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SushiApp.wsCanal.buscarCanalResponse buscarCanal(SushiApp.wsCanal.buscarCanalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceCanal/buscarCanalRequest", ReplyAction="http://WebService/ServiceCanal/buscarCanalResponse")]
        System.Threading.Tasks.Task<SushiApp.wsCanal.buscarCanalResponse> buscarCanalAsync(SushiApp.wsCanal.buscarCanalRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService/")]
    public partial class canal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int canalIdField;
        
        private string nombreCanalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int canalId {
            get {
                return this.canalIdField;
            }
            set {
                this.canalIdField = value;
                this.RaisePropertyChanged("canalId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreCanal {
            get {
                return this.nombreCanalField;
            }
            set {
                this.nombreCanalField = value;
                this.RaisePropertyChanged("nombreCanal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCanal", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class modificarCanalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsCanal.canal canal;
        
        public modificarCanalRequest() {
        }
        
        public modificarCanalRequest(SushiApp.wsCanal.canal canal) {
            this.canal = canal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCanalResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class modificarCanalResponse {
        
        public modificarCanalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCanal", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerCanalRequest {
        
        public obtenerCanalRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCanalResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerCanalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsCanal.canal[] @return;
        
        public obtenerCanalResponse() {
        }
        
        public obtenerCanalResponse(SushiApp.wsCanal.canal[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarCanal", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class agregarCanalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsCanal.canal canal;
        
        public agregarCanalRequest() {
        }
        
        public agregarCanalRequest(SushiApp.wsCanal.canal canal) {
            this.canal = canal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarCanalResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class agregarCanalResponse {
        
        public agregarCanalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCanal", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class eliminarCanalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarCanalRequest() {
        }
        
        public eliminarCanalRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCanalResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class eliminarCanalResponse {
        
        public eliminarCanalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarCanal", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class buscarCanalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarCanalRequest() {
        }
        
        public buscarCanalRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarCanalResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class buscarCanalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsCanal.canal @return;
        
        public buscarCanalResponse() {
        }
        
        public buscarCanalResponse(SushiApp.wsCanal.canal @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceCanalChannel : SushiApp.wsCanal.ServiceCanal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCanalClient : System.ServiceModel.ClientBase<SushiApp.wsCanal.ServiceCanal>, SushiApp.wsCanal.ServiceCanal {
        
        public ServiceCanalClient() {
        }
        
        public ServiceCanalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCanalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCanalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCanalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsCanal.modificarCanalResponse SushiApp.wsCanal.ServiceCanal.modificarCanal(SushiApp.wsCanal.modificarCanalRequest request) {
            return base.Channel.modificarCanal(request);
        }
        
        public void modificarCanal(SushiApp.wsCanal.canal canal) {
            SushiApp.wsCanal.modificarCanalRequest inValue = new SushiApp.wsCanal.modificarCanalRequest();
            inValue.canal = canal;
            SushiApp.wsCanal.modificarCanalResponse retVal = ((SushiApp.wsCanal.ServiceCanal)(this)).modificarCanal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsCanal.modificarCanalResponse> SushiApp.wsCanal.ServiceCanal.modificarCanalAsync(SushiApp.wsCanal.modificarCanalRequest request) {
            return base.Channel.modificarCanalAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsCanal.modificarCanalResponse> modificarCanalAsync(SushiApp.wsCanal.canal canal) {
            SushiApp.wsCanal.modificarCanalRequest inValue = new SushiApp.wsCanal.modificarCanalRequest();
            inValue.canal = canal;
            return ((SushiApp.wsCanal.ServiceCanal)(this)).modificarCanalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsCanal.obtenerCanalResponse SushiApp.wsCanal.ServiceCanal.obtenerCanal(SushiApp.wsCanal.obtenerCanalRequest request) {
            return base.Channel.obtenerCanal(request);
        }
        
        public SushiApp.wsCanal.canal[] obtenerCanal() {
            SushiApp.wsCanal.obtenerCanalRequest inValue = new SushiApp.wsCanal.obtenerCanalRequest();
            SushiApp.wsCanal.obtenerCanalResponse retVal = ((SushiApp.wsCanal.ServiceCanal)(this)).obtenerCanal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsCanal.obtenerCanalResponse> SushiApp.wsCanal.ServiceCanal.obtenerCanalAsync(SushiApp.wsCanal.obtenerCanalRequest request) {
            return base.Channel.obtenerCanalAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsCanal.obtenerCanalResponse> obtenerCanalAsync() {
            SushiApp.wsCanal.obtenerCanalRequest inValue = new SushiApp.wsCanal.obtenerCanalRequest();
            return ((SushiApp.wsCanal.ServiceCanal)(this)).obtenerCanalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsCanal.agregarCanalResponse SushiApp.wsCanal.ServiceCanal.agregarCanal(SushiApp.wsCanal.agregarCanalRequest request) {
            return base.Channel.agregarCanal(request);
        }
        
        public void agregarCanal(SushiApp.wsCanal.canal canal) {
            SushiApp.wsCanal.agregarCanalRequest inValue = new SushiApp.wsCanal.agregarCanalRequest();
            inValue.canal = canal;
            SushiApp.wsCanal.agregarCanalResponse retVal = ((SushiApp.wsCanal.ServiceCanal)(this)).agregarCanal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsCanal.agregarCanalResponse> SushiApp.wsCanal.ServiceCanal.agregarCanalAsync(SushiApp.wsCanal.agregarCanalRequest request) {
            return base.Channel.agregarCanalAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsCanal.agregarCanalResponse> agregarCanalAsync(SushiApp.wsCanal.canal canal) {
            SushiApp.wsCanal.agregarCanalRequest inValue = new SushiApp.wsCanal.agregarCanalRequest();
            inValue.canal = canal;
            return ((SushiApp.wsCanal.ServiceCanal)(this)).agregarCanalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsCanal.eliminarCanalResponse SushiApp.wsCanal.ServiceCanal.eliminarCanal(SushiApp.wsCanal.eliminarCanalRequest request) {
            return base.Channel.eliminarCanal(request);
        }
        
        public void eliminarCanal(int id) {
            SushiApp.wsCanal.eliminarCanalRequest inValue = new SushiApp.wsCanal.eliminarCanalRequest();
            inValue.id = id;
            SushiApp.wsCanal.eliminarCanalResponse retVal = ((SushiApp.wsCanal.ServiceCanal)(this)).eliminarCanal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsCanal.eliminarCanalResponse> SushiApp.wsCanal.ServiceCanal.eliminarCanalAsync(SushiApp.wsCanal.eliminarCanalRequest request) {
            return base.Channel.eliminarCanalAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsCanal.eliminarCanalResponse> eliminarCanalAsync(int id) {
            SushiApp.wsCanal.eliminarCanalRequest inValue = new SushiApp.wsCanal.eliminarCanalRequest();
            inValue.id = id;
            return ((SushiApp.wsCanal.ServiceCanal)(this)).eliminarCanalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsCanal.buscarCanalResponse SushiApp.wsCanal.ServiceCanal.buscarCanal(SushiApp.wsCanal.buscarCanalRequest request) {
            return base.Channel.buscarCanal(request);
        }
        
        public SushiApp.wsCanal.canal buscarCanal(int id) {
            SushiApp.wsCanal.buscarCanalRequest inValue = new SushiApp.wsCanal.buscarCanalRequest();
            inValue.id = id;
            SushiApp.wsCanal.buscarCanalResponse retVal = ((SushiApp.wsCanal.ServiceCanal)(this)).buscarCanal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsCanal.buscarCanalResponse> SushiApp.wsCanal.ServiceCanal.buscarCanalAsync(SushiApp.wsCanal.buscarCanalRequest request) {
            return base.Channel.buscarCanalAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsCanal.buscarCanalResponse> buscarCanalAsync(int id) {
            SushiApp.wsCanal.buscarCanalRequest inValue = new SushiApp.wsCanal.buscarCanalRequest();
            inValue.id = id;
            return ((SushiApp.wsCanal.ServiceCanal)(this)).buscarCanalAsync(inValue);
        }
    }
}
