//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SushiApp.wsEmail2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsEmail2.wsEmail2Soap")]
    public interface wsEmail2Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmailConfirmacion", ReplyAction="*")]
        SushiApp.wsEmail2.EmailConfirmacionResponse EmailConfirmacion(SushiApp.wsEmail2.EmailConfirmacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmailConfirmacion", ReplyAction="*")]
        System.Threading.Tasks.Task<SushiApp.wsEmail2.EmailConfirmacionResponse> EmailConfirmacionAsync(SushiApp.wsEmail2.EmailConfirmacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmailBoleta", ReplyAction="*")]
        SushiApp.wsEmail2.EmailBoletaResponse EmailBoleta(SushiApp.wsEmail2.EmailBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmailBoleta", ReplyAction="*")]
        System.Threading.Tasks.Task<SushiApp.wsEmail2.EmailBoletaResponse> EmailBoletaAsync(SushiApp.wsEmail2.EmailBoletaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmailConfirmacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmailConfirmacion", Namespace="http://tempuri.org/", Order=0)]
        public SushiApp.wsEmail2.EmailConfirmacionRequestBody Body;
        
        public EmailConfirmacionRequest() {
        }
        
        public EmailConfirmacionRequest(SushiApp.wsEmail2.EmailConfirmacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmailConfirmacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public EmailConfirmacionRequestBody() {
        }
        
        public EmailConfirmacionRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmailConfirmacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmailConfirmacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public SushiApp.wsEmail2.EmailConfirmacionResponseBody Body;
        
        public EmailConfirmacionResponse() {
        }
        
        public EmailConfirmacionResponse(SushiApp.wsEmail2.EmailConfirmacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmailConfirmacionResponseBody {
        
        public EmailConfirmacionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmailBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmailBoleta", Namespace="http://tempuri.org/", Order=0)]
        public SushiApp.wsEmail2.EmailBoletaRequestBody Body;
        
        public EmailBoletaRequest() {
        }
        
        public EmailBoletaRequest(SushiApp.wsEmail2.EmailBoletaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmailBoletaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string boleta;
        
        public EmailBoletaRequestBody() {
        }
        
        public EmailBoletaRequestBody(string email, string boleta) {
            this.email = email;
            this.boleta = boleta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmailBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmailBoletaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SushiApp.wsEmail2.EmailBoletaResponseBody Body;
        
        public EmailBoletaResponse() {
        }
        
        public EmailBoletaResponse(SushiApp.wsEmail2.EmailBoletaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmailBoletaResponseBody {
        
        public EmailBoletaResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsEmail2SoapChannel : SushiApp.wsEmail2.wsEmail2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsEmail2SoapClient : System.ServiceModel.ClientBase<SushiApp.wsEmail2.wsEmail2Soap>, SushiApp.wsEmail2.wsEmail2Soap {
        
        public wsEmail2SoapClient() {
        }
        
        public wsEmail2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsEmail2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEmail2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEmail2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsEmail2.EmailConfirmacionResponse SushiApp.wsEmail2.wsEmail2Soap.EmailConfirmacion(SushiApp.wsEmail2.EmailConfirmacionRequest request) {
            return base.Channel.EmailConfirmacion(request);
        }
        
        public void EmailConfirmacion(string email) {
            SushiApp.wsEmail2.EmailConfirmacionRequest inValue = new SushiApp.wsEmail2.EmailConfirmacionRequest();
            inValue.Body = new SushiApp.wsEmail2.EmailConfirmacionRequestBody();
            inValue.Body.email = email;
            SushiApp.wsEmail2.EmailConfirmacionResponse retVal = ((SushiApp.wsEmail2.wsEmail2Soap)(this)).EmailConfirmacion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsEmail2.EmailConfirmacionResponse> SushiApp.wsEmail2.wsEmail2Soap.EmailConfirmacionAsync(SushiApp.wsEmail2.EmailConfirmacionRequest request) {
            return base.Channel.EmailConfirmacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsEmail2.EmailConfirmacionResponse> EmailConfirmacionAsync(string email) {
            SushiApp.wsEmail2.EmailConfirmacionRequest inValue = new SushiApp.wsEmail2.EmailConfirmacionRequest();
            inValue.Body = new SushiApp.wsEmail2.EmailConfirmacionRequestBody();
            inValue.Body.email = email;
            return ((SushiApp.wsEmail2.wsEmail2Soap)(this)).EmailConfirmacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsEmail2.EmailBoletaResponse SushiApp.wsEmail2.wsEmail2Soap.EmailBoleta(SushiApp.wsEmail2.EmailBoletaRequest request) {
            return base.Channel.EmailBoleta(request);
        }
        
        public void EmailBoleta(string email, string boleta) {
            SushiApp.wsEmail2.EmailBoletaRequest inValue = new SushiApp.wsEmail2.EmailBoletaRequest();
            inValue.Body = new SushiApp.wsEmail2.EmailBoletaRequestBody();
            inValue.Body.email = email;
            inValue.Body.boleta = boleta;
            SushiApp.wsEmail2.EmailBoletaResponse retVal = ((SushiApp.wsEmail2.wsEmail2Soap)(this)).EmailBoleta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsEmail2.EmailBoletaResponse> SushiApp.wsEmail2.wsEmail2Soap.EmailBoletaAsync(SushiApp.wsEmail2.EmailBoletaRequest request) {
            return base.Channel.EmailBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsEmail2.EmailBoletaResponse> EmailBoletaAsync(string email, string boleta) {
            SushiApp.wsEmail2.EmailBoletaRequest inValue = new SushiApp.wsEmail2.EmailBoletaRequest();
            inValue.Body = new SushiApp.wsEmail2.EmailBoletaRequestBody();
            inValue.Body.email = email;
            inValue.Body.boleta = boleta;
            return ((SushiApp.wsEmail2.wsEmail2Soap)(this)).EmailBoletaAsync(inValue);
        }
    }
}
