//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SushiApp.wsAcceso {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebService/", ConfigurationName="wsAcceso.ServiceAcceso")]
    public interface ServiceAcceso {
        
        // CODEGEN: El parámetro 'acceso' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceAcceso/modificarAccesoRequest", ReplyAction="http://WebService/ServiceAcceso/modificarAccesoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsAcceso.modificarAccesoResponse modificarAcceso(SushiApp.wsAcceso.modificarAccesoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceAcceso/modificarAccesoRequest", ReplyAction="http://WebService/ServiceAcceso/modificarAccesoResponse")]
        System.Threading.Tasks.Task<SushiApp.wsAcceso.modificarAccesoResponse> modificarAccesoAsync(SushiApp.wsAcceso.modificarAccesoRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceAcceso/eliminarAccesoRequest", ReplyAction="http://WebService/ServiceAcceso/eliminarAccesoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsAcceso.eliminarAccesoResponse eliminarAcceso(SushiApp.wsAcceso.eliminarAccesoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceAcceso/eliminarAccesoRequest", ReplyAction="http://WebService/ServiceAcceso/eliminarAccesoResponse")]
        System.Threading.Tasks.Task<SushiApp.wsAcceso.eliminarAccesoResponse> eliminarAccesoAsync(SushiApp.wsAcceso.eliminarAccesoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceAcceso/buscarAccesoRequest", ReplyAction="http://WebService/ServiceAcceso/buscarAccesoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SushiApp.wsAcceso.buscarAccesoResponse buscarAcceso(SushiApp.wsAcceso.buscarAccesoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceAcceso/buscarAccesoRequest", ReplyAction="http://WebService/ServiceAcceso/buscarAccesoResponse")]
        System.Threading.Tasks.Task<SushiApp.wsAcceso.buscarAccesoResponse> buscarAccesoAsync(SushiApp.wsAcceso.buscarAccesoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceAcceso/obtenerAccesoRequest", ReplyAction="http://WebService/ServiceAcceso/obtenerAccesoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SushiApp.wsAcceso.obtenerAccesoResponse obtenerAcceso(SushiApp.wsAcceso.obtenerAccesoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceAcceso/obtenerAccesoRequest", ReplyAction="http://WebService/ServiceAcceso/obtenerAccesoResponse")]
        System.Threading.Tasks.Task<SushiApp.wsAcceso.obtenerAccesoResponse> obtenerAccesoAsync(SushiApp.wsAcceso.obtenerAccesoRequest request);
        
        // CODEGEN: El parámetro 'acceso' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceAcceso/agregaAccesoRequest", ReplyAction="http://WebService/ServiceAcceso/agregaAccesoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsAcceso.agregaAccesoResponse agregaAcceso(SushiApp.wsAcceso.agregaAccesoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServiceAcceso/agregaAccesoRequest", ReplyAction="http://WebService/ServiceAcceso/agregaAccesoResponse")]
        System.Threading.Tasks.Task<SushiApp.wsAcceso.agregaAccesoResponse> agregaAccesoAsync(SushiApp.wsAcceso.agregaAccesoRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService/")]
    public partial class acceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int accesoIdField;
        
        private int paginaIdField;
        
        private int perfilIdField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int accesoId {
            get {
                return this.accesoIdField;
            }
            set {
                this.accesoIdField = value;
                this.RaisePropertyChanged("accesoId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int paginaId {
            get {
                return this.paginaIdField;
            }
            set {
                this.paginaIdField = value;
                this.RaisePropertyChanged("paginaId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int perfilId {
            get {
                return this.perfilIdField;
            }
            set {
                this.perfilIdField = value;
                this.RaisePropertyChanged("perfilId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAcceso", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class modificarAccesoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsAcceso.acceso acceso;
        
        public modificarAccesoRequest() {
        }
        
        public modificarAccesoRequest(SushiApp.wsAcceso.acceso acceso) {
            this.acceso = acceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAccesoResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class modificarAccesoResponse {
        
        public modificarAccesoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAcceso", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class eliminarAccesoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarAccesoRequest() {
        }
        
        public eliminarAccesoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAccesoResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class eliminarAccesoResponse {
        
        public eliminarAccesoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarAcceso", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class buscarAccesoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarAccesoRequest() {
        }
        
        public buscarAccesoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarAccesoResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class buscarAccesoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsAcceso.acceso @return;
        
        public buscarAccesoResponse() {
        }
        
        public buscarAccesoResponse(SushiApp.wsAcceso.acceso @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAcceso", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerAccesoRequest {
        
        public obtenerAccesoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAccesoResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerAccesoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsAcceso.acceso[] @return;
        
        public obtenerAccesoResponse() {
        }
        
        public obtenerAccesoResponse(SushiApp.wsAcceso.acceso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregaAcceso", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class agregaAccesoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsAcceso.acceso acceso;
        
        public agregaAccesoRequest() {
        }
        
        public agregaAccesoRequest(SushiApp.wsAcceso.acceso acceso) {
            this.acceso = acceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregaAccesoResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class agregaAccesoResponse {
        
        public agregaAccesoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceAccesoChannel : SushiApp.wsAcceso.ServiceAcceso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAccesoClient : System.ServiceModel.ClientBase<SushiApp.wsAcceso.ServiceAcceso>, SushiApp.wsAcceso.ServiceAcceso {
        
        public ServiceAccesoClient() {
        }
        
        public ServiceAccesoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAccesoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAccesoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAccesoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsAcceso.modificarAccesoResponse SushiApp.wsAcceso.ServiceAcceso.modificarAcceso(SushiApp.wsAcceso.modificarAccesoRequest request) {
            return base.Channel.modificarAcceso(request);
        }
        
        public void modificarAcceso(SushiApp.wsAcceso.acceso acceso) {
            SushiApp.wsAcceso.modificarAccesoRequest inValue = new SushiApp.wsAcceso.modificarAccesoRequest();
            inValue.acceso = acceso;
            SushiApp.wsAcceso.modificarAccesoResponse retVal = ((SushiApp.wsAcceso.ServiceAcceso)(this)).modificarAcceso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsAcceso.modificarAccesoResponse> SushiApp.wsAcceso.ServiceAcceso.modificarAccesoAsync(SushiApp.wsAcceso.modificarAccesoRequest request) {
            return base.Channel.modificarAccesoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsAcceso.modificarAccesoResponse> modificarAccesoAsync(SushiApp.wsAcceso.acceso acceso) {
            SushiApp.wsAcceso.modificarAccesoRequest inValue = new SushiApp.wsAcceso.modificarAccesoRequest();
            inValue.acceso = acceso;
            return ((SushiApp.wsAcceso.ServiceAcceso)(this)).modificarAccesoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsAcceso.eliminarAccesoResponse SushiApp.wsAcceso.ServiceAcceso.eliminarAcceso(SushiApp.wsAcceso.eliminarAccesoRequest request) {
            return base.Channel.eliminarAcceso(request);
        }
        
        public void eliminarAcceso(int id) {
            SushiApp.wsAcceso.eliminarAccesoRequest inValue = new SushiApp.wsAcceso.eliminarAccesoRequest();
            inValue.id = id;
            SushiApp.wsAcceso.eliminarAccesoResponse retVal = ((SushiApp.wsAcceso.ServiceAcceso)(this)).eliminarAcceso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsAcceso.eliminarAccesoResponse> SushiApp.wsAcceso.ServiceAcceso.eliminarAccesoAsync(SushiApp.wsAcceso.eliminarAccesoRequest request) {
            return base.Channel.eliminarAccesoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsAcceso.eliminarAccesoResponse> eliminarAccesoAsync(int id) {
            SushiApp.wsAcceso.eliminarAccesoRequest inValue = new SushiApp.wsAcceso.eliminarAccesoRequest();
            inValue.id = id;
            return ((SushiApp.wsAcceso.ServiceAcceso)(this)).eliminarAccesoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsAcceso.buscarAccesoResponse SushiApp.wsAcceso.ServiceAcceso.buscarAcceso(SushiApp.wsAcceso.buscarAccesoRequest request) {
            return base.Channel.buscarAcceso(request);
        }
        
        public SushiApp.wsAcceso.acceso buscarAcceso(int id) {
            SushiApp.wsAcceso.buscarAccesoRequest inValue = new SushiApp.wsAcceso.buscarAccesoRequest();
            inValue.id = id;
            SushiApp.wsAcceso.buscarAccesoResponse retVal = ((SushiApp.wsAcceso.ServiceAcceso)(this)).buscarAcceso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsAcceso.buscarAccesoResponse> SushiApp.wsAcceso.ServiceAcceso.buscarAccesoAsync(SushiApp.wsAcceso.buscarAccesoRequest request) {
            return base.Channel.buscarAccesoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsAcceso.buscarAccesoResponse> buscarAccesoAsync(int id) {
            SushiApp.wsAcceso.buscarAccesoRequest inValue = new SushiApp.wsAcceso.buscarAccesoRequest();
            inValue.id = id;
            return ((SushiApp.wsAcceso.ServiceAcceso)(this)).buscarAccesoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsAcceso.obtenerAccesoResponse SushiApp.wsAcceso.ServiceAcceso.obtenerAcceso(SushiApp.wsAcceso.obtenerAccesoRequest request) {
            return base.Channel.obtenerAcceso(request);
        }
        
        public SushiApp.wsAcceso.acceso[] obtenerAcceso() {
            SushiApp.wsAcceso.obtenerAccesoRequest inValue = new SushiApp.wsAcceso.obtenerAccesoRequest();
            SushiApp.wsAcceso.obtenerAccesoResponse retVal = ((SushiApp.wsAcceso.ServiceAcceso)(this)).obtenerAcceso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsAcceso.obtenerAccesoResponse> SushiApp.wsAcceso.ServiceAcceso.obtenerAccesoAsync(SushiApp.wsAcceso.obtenerAccesoRequest request) {
            return base.Channel.obtenerAccesoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsAcceso.obtenerAccesoResponse> obtenerAccesoAsync() {
            SushiApp.wsAcceso.obtenerAccesoRequest inValue = new SushiApp.wsAcceso.obtenerAccesoRequest();
            return ((SushiApp.wsAcceso.ServiceAcceso)(this)).obtenerAccesoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsAcceso.agregaAccesoResponse SushiApp.wsAcceso.ServiceAcceso.agregaAcceso(SushiApp.wsAcceso.agregaAccesoRequest request) {
            return base.Channel.agregaAcceso(request);
        }
        
        public void agregaAcceso(SushiApp.wsAcceso.acceso acceso) {
            SushiApp.wsAcceso.agregaAccesoRequest inValue = new SushiApp.wsAcceso.agregaAccesoRequest();
            inValue.acceso = acceso;
            SushiApp.wsAcceso.agregaAccesoResponse retVal = ((SushiApp.wsAcceso.ServiceAcceso)(this)).agregaAcceso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsAcceso.agregaAccesoResponse> SushiApp.wsAcceso.ServiceAcceso.agregaAccesoAsync(SushiApp.wsAcceso.agregaAccesoRequest request) {
            return base.Channel.agregaAccesoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsAcceso.agregaAccesoResponse> agregaAccesoAsync(SushiApp.wsAcceso.acceso acceso) {
            SushiApp.wsAcceso.agregaAccesoRequest inValue = new SushiApp.wsAcceso.agregaAccesoRequest();
            inValue.acceso = acceso;
            return ((SushiApp.wsAcceso.ServiceAcceso)(this)).agregaAccesoAsync(inValue);
        }
    }
}
