//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SushiApp.wsPagina {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebService/", ConfigurationName="wsPagina.ServicePagina")]
    public interface ServicePagina {
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServicePagina/eliminarPaginaRequest", ReplyAction="http://WebService/ServicePagina/eliminarPaginaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsPagina.eliminarPaginaResponse eliminarPagina(SushiApp.wsPagina.eliminarPaginaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServicePagina/eliminarPaginaRequest", ReplyAction="http://WebService/ServicePagina/eliminarPaginaResponse")]
        System.Threading.Tasks.Task<SushiApp.wsPagina.eliminarPaginaResponse> eliminarPaginaAsync(SushiApp.wsPagina.eliminarPaginaRequest request);
        
        // CODEGEN: El parámetro 'pagina' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServicePagina/agregarPaginaRequest", ReplyAction="http://WebService/ServicePagina/agregarPaginaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsPagina.agregarPaginaResponse agregarPagina(SushiApp.wsPagina.agregarPaginaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServicePagina/agregarPaginaRequest", ReplyAction="http://WebService/ServicePagina/agregarPaginaResponse")]
        System.Threading.Tasks.Task<SushiApp.wsPagina.agregarPaginaResponse> agregarPaginaAsync(SushiApp.wsPagina.agregarPaginaRequest request);
        
        // CODEGEN: El parámetro 'pagina' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServicePagina/modificarPaginaRequest", ReplyAction="http://WebService/ServicePagina/modificarPaginaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SushiApp.wsPagina.modificarPaginaResponse modificarPagina(SushiApp.wsPagina.modificarPaginaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServicePagina/modificarPaginaRequest", ReplyAction="http://WebService/ServicePagina/modificarPaginaResponse")]
        System.Threading.Tasks.Task<SushiApp.wsPagina.modificarPaginaResponse> modificarPaginaAsync(SushiApp.wsPagina.modificarPaginaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServicePagina/obtenerPaginaRequest", ReplyAction="http://WebService/ServicePagina/obtenerPaginaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SushiApp.wsPagina.obtenerPaginaResponse obtenerPagina(SushiApp.wsPagina.obtenerPaginaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServicePagina/obtenerPaginaRequest", ReplyAction="http://WebService/ServicePagina/obtenerPaginaResponse")]
        System.Threading.Tasks.Task<SushiApp.wsPagina.obtenerPaginaResponse> obtenerPaginaAsync(SushiApp.wsPagina.obtenerPaginaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServicePagina/buscarPaginaRequest", ReplyAction="http://WebService/ServicePagina/buscarPaginaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SushiApp.wsPagina.buscarPaginaResponse buscarPagina(SushiApp.wsPagina.buscarPaginaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/ServicePagina/buscarPaginaRequest", ReplyAction="http://WebService/ServicePagina/buscarPaginaResponse")]
        System.Threading.Tasks.Task<SushiApp.wsPagina.buscarPaginaResponse> buscarPaginaAsync(SushiApp.wsPagina.buscarPaginaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPagina", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class eliminarPaginaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarPaginaRequest() {
        }
        
        public eliminarPaginaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPaginaResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class eliminarPaginaResponse {
        
        public eliminarPaginaResponse() {
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebService/")]
    public partial class pagina : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pagina1Field;
        
        private int paginaIdField;
        
        private string urlPaginaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("pagina", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string pagina1 {
            get {
                return this.pagina1Field;
            }
            set {
                this.pagina1Field = value;
                this.RaisePropertyChanged("pagina1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int paginaId {
            get {
                return this.paginaIdField;
            }
            set {
                this.paginaIdField = value;
                this.RaisePropertyChanged("paginaId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string urlPagina {
            get {
                return this.urlPaginaField;
            }
            set {
                this.urlPaginaField = value;
                this.RaisePropertyChanged("urlPagina");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarPagina", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class agregarPaginaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsPagina.pagina pagina;
        
        public agregarPaginaRequest() {
        }
        
        public agregarPaginaRequest(SushiApp.wsPagina.pagina pagina) {
            this.pagina = pagina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarPaginaResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class agregarPaginaResponse {
        
        public agregarPaginaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPagina", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class modificarPaginaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsPagina.pagina pagina;
        
        public modificarPaginaRequest() {
        }
        
        public modificarPaginaRequest(SushiApp.wsPagina.pagina pagina) {
            this.pagina = pagina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPaginaResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class modificarPaginaResponse {
        
        public modificarPaginaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPagina", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerPaginaRequest {
        
        public obtenerPaginaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPaginaResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class obtenerPaginaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsPagina.pagina[] @return;
        
        public obtenerPaginaResponse() {
        }
        
        public obtenerPaginaResponse(SushiApp.wsPagina.pagina[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPagina", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class buscarPaginaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarPaginaRequest() {
        }
        
        public buscarPaginaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPaginaResponse", WrapperNamespace="http://WebService/", IsWrapped=true)]
    public partial class buscarPaginaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SushiApp.wsPagina.pagina @return;
        
        public buscarPaginaResponse() {
        }
        
        public buscarPaginaResponse(SushiApp.wsPagina.pagina @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicePaginaChannel : SushiApp.wsPagina.ServicePagina, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePaginaClient : System.ServiceModel.ClientBase<SushiApp.wsPagina.ServicePagina>, SushiApp.wsPagina.ServicePagina {
        
        public ServicePaginaClient() {
        }
        
        public ServicePaginaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePaginaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePaginaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePaginaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsPagina.eliminarPaginaResponse SushiApp.wsPagina.ServicePagina.eliminarPagina(SushiApp.wsPagina.eliminarPaginaRequest request) {
            return base.Channel.eliminarPagina(request);
        }
        
        public void eliminarPagina(int id) {
            SushiApp.wsPagina.eliminarPaginaRequest inValue = new SushiApp.wsPagina.eliminarPaginaRequest();
            inValue.id = id;
            SushiApp.wsPagina.eliminarPaginaResponse retVal = ((SushiApp.wsPagina.ServicePagina)(this)).eliminarPagina(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsPagina.eliminarPaginaResponse> SushiApp.wsPagina.ServicePagina.eliminarPaginaAsync(SushiApp.wsPagina.eliminarPaginaRequest request) {
            return base.Channel.eliminarPaginaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsPagina.eliminarPaginaResponse> eliminarPaginaAsync(int id) {
            SushiApp.wsPagina.eliminarPaginaRequest inValue = new SushiApp.wsPagina.eliminarPaginaRequest();
            inValue.id = id;
            return ((SushiApp.wsPagina.ServicePagina)(this)).eliminarPaginaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsPagina.agregarPaginaResponse SushiApp.wsPagina.ServicePagina.agregarPagina(SushiApp.wsPagina.agregarPaginaRequest request) {
            return base.Channel.agregarPagina(request);
        }
        
        public void agregarPagina(SushiApp.wsPagina.pagina pagina) {
            SushiApp.wsPagina.agregarPaginaRequest inValue = new SushiApp.wsPagina.agregarPaginaRequest();
            inValue.pagina = pagina;
            SushiApp.wsPagina.agregarPaginaResponse retVal = ((SushiApp.wsPagina.ServicePagina)(this)).agregarPagina(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsPagina.agregarPaginaResponse> SushiApp.wsPagina.ServicePagina.agregarPaginaAsync(SushiApp.wsPagina.agregarPaginaRequest request) {
            return base.Channel.agregarPaginaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsPagina.agregarPaginaResponse> agregarPaginaAsync(SushiApp.wsPagina.pagina pagina) {
            SushiApp.wsPagina.agregarPaginaRequest inValue = new SushiApp.wsPagina.agregarPaginaRequest();
            inValue.pagina = pagina;
            return ((SushiApp.wsPagina.ServicePagina)(this)).agregarPaginaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsPagina.modificarPaginaResponse SushiApp.wsPagina.ServicePagina.modificarPagina(SushiApp.wsPagina.modificarPaginaRequest request) {
            return base.Channel.modificarPagina(request);
        }
        
        public void modificarPagina(SushiApp.wsPagina.pagina pagina) {
            SushiApp.wsPagina.modificarPaginaRequest inValue = new SushiApp.wsPagina.modificarPaginaRequest();
            inValue.pagina = pagina;
            SushiApp.wsPagina.modificarPaginaResponse retVal = ((SushiApp.wsPagina.ServicePagina)(this)).modificarPagina(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsPagina.modificarPaginaResponse> SushiApp.wsPagina.ServicePagina.modificarPaginaAsync(SushiApp.wsPagina.modificarPaginaRequest request) {
            return base.Channel.modificarPaginaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsPagina.modificarPaginaResponse> modificarPaginaAsync(SushiApp.wsPagina.pagina pagina) {
            SushiApp.wsPagina.modificarPaginaRequest inValue = new SushiApp.wsPagina.modificarPaginaRequest();
            inValue.pagina = pagina;
            return ((SushiApp.wsPagina.ServicePagina)(this)).modificarPaginaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsPagina.obtenerPaginaResponse SushiApp.wsPagina.ServicePagina.obtenerPagina(SushiApp.wsPagina.obtenerPaginaRequest request) {
            return base.Channel.obtenerPagina(request);
        }
        
        public SushiApp.wsPagina.pagina[] obtenerPagina() {
            SushiApp.wsPagina.obtenerPaginaRequest inValue = new SushiApp.wsPagina.obtenerPaginaRequest();
            SushiApp.wsPagina.obtenerPaginaResponse retVal = ((SushiApp.wsPagina.ServicePagina)(this)).obtenerPagina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsPagina.obtenerPaginaResponse> SushiApp.wsPagina.ServicePagina.obtenerPaginaAsync(SushiApp.wsPagina.obtenerPaginaRequest request) {
            return base.Channel.obtenerPaginaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsPagina.obtenerPaginaResponse> obtenerPaginaAsync() {
            SushiApp.wsPagina.obtenerPaginaRequest inValue = new SushiApp.wsPagina.obtenerPaginaRequest();
            return ((SushiApp.wsPagina.ServicePagina)(this)).obtenerPaginaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SushiApp.wsPagina.buscarPaginaResponse SushiApp.wsPagina.ServicePagina.buscarPagina(SushiApp.wsPagina.buscarPaginaRequest request) {
            return base.Channel.buscarPagina(request);
        }
        
        public SushiApp.wsPagina.pagina buscarPagina(int id) {
            SushiApp.wsPagina.buscarPaginaRequest inValue = new SushiApp.wsPagina.buscarPaginaRequest();
            inValue.id = id;
            SushiApp.wsPagina.buscarPaginaResponse retVal = ((SushiApp.wsPagina.ServicePagina)(this)).buscarPagina(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SushiApp.wsPagina.buscarPaginaResponse> SushiApp.wsPagina.ServicePagina.buscarPaginaAsync(SushiApp.wsPagina.buscarPaginaRequest request) {
            return base.Channel.buscarPaginaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SushiApp.wsPagina.buscarPaginaResponse> buscarPaginaAsync(int id) {
            SushiApp.wsPagina.buscarPaginaRequest inValue = new SushiApp.wsPagina.buscarPaginaRequest();
            inValue.id = id;
            return ((SushiApp.wsPagina.ServicePagina)(this)).buscarPaginaAsync(inValue);
        }
    }
}
